fails:Array.new raises an ArgumentError when passed a too large size
fails:Array.new checks whether the passed argument responds to #to_ary
fails:Array.new checks whether the passed argument responds to #to_int if they don't respond to #to_ary
fails:Array.new will fail if a to_ary is supplied as the first argument and a second argument is given
