breaks:Kernel.throw raises a NameError if there is no catch block for the symbol
