fails:Kernel.throw raises ArgumentError if 3 or more arguments provided
fails:Kernel.throw raises TypeError if the first argument is not a symbol
fails:Kernel#throw is a private method
